# # Daily Habit Tracker Bot Configuration

# # Bot settings
# bot_name: DailyHabitBot
# timezone: America/New_York
# language: en

# # Data storage configuration
# data_storage:
#   type: file_system
#   directory: data

# # Reminders settings
# reminders:
#   enabled: true
#   reminder_time: "09:00"  # Time in HH:MM format (24-hour clock)
#   reminder_message: "Hey there! Don't forget to log your habits for today."

# # Habit categories
# habit_categories:
#   - exercise
#   - reading
#   - meditation
#   - coding
#   - writing

# # Responses
# responses:
#   greeting: "Hello! I'm here to help you track your daily habits. Let's get started!"
#   help: "You can use commands like 'log exercise' or 'show habits' to interact with me."
#   invalid_command: "I'm sorry, I don't understand that command. Type 'help' to see the available options."
#   habit_logged: "Great job! Your {{habit}} habit for today has been logged."
#   habit_already_logged: "You've already logged your {{habit}} habit for today."
#   habits_list:
#     intro: "Here are your logged habits for today:"
#     empty: "You haven't logged any habits yet today."
#   error: "Oops! Something went wrong. Please try again later."

# # Command aliases
# command_aliases:
#   - log: ["record", "track"]
#   - show: ["list", "display"]

# # Logging configuration
# logging:
#   level: info
#   file: bot.log
# pipeline:
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# #   - name: WhitespaceTokenizer
# #   - name: RegexFeaturizer
# #   - name: LexicalSyntacticFeaturizer
# #   - name: CountVectorsFeaturizer
# #   - name: CountVectorsFeaturizer
# #     analyzer: char_wb
# #     min_ngram: 1
# #     max_ngram: 4
# #   - name: DIETClassifier
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: EntitySynonymMapper
# #   - name: ResponseSelector
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: FallbackClassifier
# #     threshold: 0.3
# #     ambiguity_threshold: 0.1
# policies:
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy
# #   - name: RulePolicy
# #   - name: UnexpecTEDIntentPolicy
# #     max_history: 5
# #     epochs: 100
# #   - name: TEDPolicy
# #     max_history: 5
# #     epochs: 100
# #     constrain_similarities: true
#######################################################
# Configuration for Rasa NLU
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100

# Configuration for Rasa Core
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy

# Configuration for Response Selector (if using it)
# You can uncomment this section if you're using Rasa Response Selector
# responses:
#   fetch: true

  # Define other rules here based on your rules.yml content
